import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import AuthNavBar from "@/components/ui/layouts/auth-nav";
import StoreProvider from "@/redux/provider/StoreProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Auth",
  description: "Generated by create next app",
};

export default function AuthLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <StoreProvider>
          <AuthNavBar />
          <div className="flex min-h-screen bg-[#d7daf7]">
            <div className="flex w-full justify-center items-center px-6 pb-12">
              {children}
            </div>
          </div>
        </StoreProvider>
      </body>
    </html>
  );
}
