import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Footer from "@/components/ui/layouts/footer";
import CustomNavBar from "@/components/ui/layouts/navbar";
import StoreProvider from "@/redux/provider/StoreProvider";
import { ToastProvider } from "@/components/ui/ToastContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "EventBuddy",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased min-h-screen flex flex-col`}
        suppressHydrationWarning={true}
      >
        {/* ✅ This fills available vertical space */}
        <StoreProvider>
          <ToastProvider>
            <CustomNavBar />
            <main className="flex-1">{children}</main>

            {/* ✅ Always at the bottom */}
            <Footer />
          </ToastProvider>
        </StoreProvider>
      </body>
    </html>
  );
}
